### ISSUE TITLE
Broken link for combine script

### ISSUE THREAD

**Issue by toyowata** [ARMmbed/mbed-bootloader-extended#2]
The build instruction [here](https://github.com/armmbed/mbed-bootloader-extended#build-instructions) explains:

> Use this [script](https://github.com/ARMmbed/mbed-cloud-client-example/blob/master/tools/combine_bootloader_with_app.py) to combine the bootloader with application `python tools/combine_bootloader_with_app.py -a {application.bin} -b {bootloader.bin} --app-offset {application-start-address} --header-offset {firmware_metadata_header_address} -o {combined.bin}`.

But the link is broken because of obsoleting in the mbed-cloud-client-example [2.0.0 release](https://github.com/ARMmbed/mbed-cloud-client-example/blob/master/CHANGELOG.md#release-200-26092018).

> * The example uses Mbed OS bootloader binaries and the new Mbed OS feature `FEATURE_BOOTLOADER`. This feature makes the `combine_bootloader_with_app.py` script obsolete. We have removed the obsolete script and old bootloader binaries from the application repository.

**Comment by 0xc0170** [comment]
The repository was deprecated and it's being archived now. We are closing all issues/pull requests.
